### ISSUE TITLE
Does not seem to work on symbols defined outside `Unitful.jl`, e.g, `UnitfulAtomic.jl`

### ISSUE THREAD

**Issue by singularitti** [michikawa07/UnitfulParsableString.jl#3]
For example,

```julia
julia> string(1u"bohr")
"1a₀"

julia> Unitful.uparse(string(1u"bohr"); unit_context=[Unitful,UnitfulAtomic])
ERROR: ArgumentError: Symbol a₀ could not be found in unit modules Module[Unitful, UnitfulAtomic]
Stacktrace:
 [1] lookup_units(unitmods::Vector{Module}, sym::Symbol)
   @ Unitful ~/.julia/packages/Unitful/SUQzL/src/user.jl:707
 [2] lookup_units(unitmods::Vector{Module}, ex::Expr)
   @ Unitful ~/.julia/packages/Unitful/SUQzL/src/user.jl:674
 [3] uparse(str::String; unit_context::Vector{Module})
   @ Unitful ~/.julia/packages/Unitful/SUQzL/src/user.jl:662
 [4] top-level scope
   @ REPL[20]:1
```

```julia
julia> versioninfo()
Julia Version 1.8.1
Commit afb6c60d69a (2022-09-06 15:09 UTC)
```

**Comment by Shinobi-mechatro** [comment]
I could see the same error now.  
The problem does not seem to be that it is outside defined, but that the variable name and the display name (maybe return value of `abbr(x)`) are different.
```julia
julia> uparse(string(1u"μ_N"); unit_context=[Unitful,UnitfulAtomic])
1 μ_N
```

`UnitfulAtomic.bohr` is defined as variable `a0_au`, which is different from the display name `a₀`.
I think I can fix this problem, so I'll get to it.
Thank you for your report. It is very helpful.

**Comment by michikawa07** [comment]
I could see the same error now.  
The problem does not seem to be that it is outside defined, but that the variable name and the display name (maybe return value of `abbr(x)`) are different.
```julia
julia> uparse(string(1u"μ_N"); unit_context=[Unitful,UnitfulAtomic])
1 μ_N
```

`UnitfulAtomic.bohr` is defined as variable `a0_au`, which is different from the display name `a₀`.
I think I can fix this problem, so I'll get to it.
Thank you for your report. It is very helpful.

**Comment by michikawa07** [comment]
Although it is a rough implementation, I have added support for units such as `u"bohr"`, where the abbr and variable symbols are different.
I hope you will check it.

Checks if `abbr(x)` can parse to the original `x` in the `Unitful` and `Unitful.unitmodules` namespace.
If not, it searches for a symbol that can be parsed into the original `x`. 
If the symbol is found in the namespase, it returns it; otherwise, it returns a warning.
```julia
julia> using UnitfulAtomic

julia> str = string(1.0u"bohr")
┌ Warning: A symbol to be parsed into "a₀" could not be found in the given "Module[Unitful]"
└ @ UnitfulParsableString
"1.0a₀"

julia> uparse(str, unit_context=[Unitful, UnitfulAtomic])
ERROR: ArgumentError: Symbol a₀ could not be found in unit modules Module[Unitful, UnitfulAtomic]
Stacktrace:
 [1] lookup_units(unitmods::Vector{Module}, sym::Symbol)
   @ Unitful C:\Users\michi\.julia\packages\Unitful\SUQzL\src\user.jl:707
 [2] lookup_units(unitmods::Vector{Module}, ex::Expr)
   @ Unitful C:\Users\michi\.julia\packages\Unitful\SUQzL\src\user.jl:674
 [3] uparse(str::String; unit_context::Vector{Module})
   @ Unitful C:\Users\michi\.julia\packages\Unitful\SUQzL\src\user.jl:662
 [4] top-level scope
   @ REPL[117]:1
```

In the following example, `Unitful` and `UnitfulAtomic` modules are used to determine if parsing is possible.
`UnitfulAtomic` is automatically registered to `Unitful.unitmodules`.
```julia
julia> using UnitfulAtomic

julia> str = string(1.0u"bohr")
"1.0bohr"

julia> uparse(str, unit_context=[Unitful, UnitfulAtomic])
1.0 a₀
```
