### ISSUE TITLE
Is it necessary to print `NoUnits` type as "NoUnits"?

### ISSUE THREAD

**Issue by singularitti** [michikawa07/UnitfulParsableString.jl#6]
It seems that this package overrides [`string` for `NoUnits` types as](https://github.com/michikawa07/UnitfulParsableString.jl/blob/b99cfd3ad6c3f5e66ab12fafa9d1ca6a13adf9d0/src/UnitfulParsableString.jl#L220-L222):

```julia
function Unitful.string(x::typeof(NoUnits))
	"NoUnits"
end
```

And it causes some quantities to be printed as `123NoUnits`, which is not very readable. Could `NoUnits` just be not printed?

**Comment by michikawa07** [comment]
Thanks for your use my package.

I think too that `"123NoUnits"`  is not readable . So, I want to update and improve the behavior about `NoUnits`

Firstly, could you show me the concrete code where `"123NoUnits"` is output. I could not find (please see my below check).

```julia
julia> 123NoUnits
123

julia> 123NoUnits |> string
"123"

julia> 123u"m"/ 1u"m" |> string
"123.0"

julia> 123u"m"/ 1u"m" |> NoUnits |> string
"123.0"

julia> 123u"m"/ 1u"mm" |> string
"123.0(m/mm)"

julia> 123u"m"/ 1u"mm" |> NoUnits |> string
"123000.0"

julia> NoUnits


julia> NoUnits |> string
"NoUnits"
```

(I show my opinion at present)
The reason why `NoUnits` are printed is to satisfy the parsability of the string of `NoUnits` unit.
```julia 
julia> uparse(string(NoUnits)) == NoUnits
true
```

**Comment by singularitti** [comment]
Hi @michikawa07, thank you for your prompt reply!

I guess you need to put it in a container like an `Array` (but a `Tuple` works fine):

```julia
julia> x = 123u"m"/ 1u"m"
123.0

julia> y = 1u"m"
1 m

julia> z = 2.0u"kg"
2.0 kg

julia> [x, y, z] .|> string
3-element Vector{String}:
 "123.0NoUnits"
 "1.0m"
 "2.0kg"

julia> [x, y, z] |> string
"[123.0NoUnits, 1.0m, 2.0kg]"

julia> (x, y, z) |> string
"(123.0, 1 m, 2.0 kg)"

julia> (x, y, z) .|> string
("123.0", "1m", "2.0kg")

julia> typeof([x, y, z])
Vector{Quantity{Float64}} (alias for Array{Quantity{Float64}, 1})

julia> typeof((x, y, z))
Tuple{Float64, Quantity{Int64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}, Quantity{Float64, 𝐌, Unitful.FreeUnits{(kg,), 𝐌, nothing}}}
```

**Comment by michikawa07** [comment]
Thank you!!

I was not aware of that behavior. Very helpful.
Given that `Tuple` is working well, I wonder if it is a property of Array{Quantity} rather than broadcast.

```julia 
julia> [x, y, z] .|>  typeof
3-element Vector{DataType}:
 Quantity{Float64, NoDims, Unitful.FreeUnits{(), NoDims, nothing}}
 Quantity{Float64, 𝐋, Unitful.FreeUnits{(m,), 𝐋, nothing}}
 Quantity{Float64, 𝐌, Unitful.FreeUnits{(kg,), 𝐌, nothing}}

julia> Quantity{Float64, NoDims, Unitful.FreeUnits{(), NoDims, nothing}}(1) |> string
"1.0"
```

For the time being, I made the following changes to avoid the case where the `Quantitiy` unit is `NoUnits`.
```julia 
function Unitful.string(x::Quantity)
	v = string(x.val)
	u = string(unit(x))
	unit(x) == NoUnits && return v # new line
	val = has_value_bracket(x.val) ? string("(", v, ")") : v
	uni = has_unit_bracket(unit(x))  ? string("(", u, ")") : u
	sep = has_value_bracket(x.val) && has_unit_bracket(unit(x)) ? "*" : ""
	string(val, sep, uni)
end
```

 ```julia
julia> [x, y, z] .|> string
3-element Vector{String}:
 "123.0"
 "1.0m"
 "2.0kg"

julia> [x, y, z] |> string
"[123.0, 1.0m, 2.0kg]"
```

**Comment by singularitti** [comment]
Good, and it seems to work with custom types:

```julia
julia> struct A{T}
           a::T
           b::T
           c::T
       end

julia> A{Quantity{Float64}}(x, y, z) |> string
"A{Quantity{Float64}}(123.0, 1.0 m, 2.0 kg)"
```

**Comment by singularitti** [comment]
I sense a version is released to fix this issue. Should I close this issue?

**Comment by michikawa07** [comment]
Sorry for the late reply!
I was thinking about this area ...

> Good, and it seems to work with custom types:
> 
> ```julia
> julia> struct A{T}
>            a::T
>            b::T
>            c::T
>        end
> 
> julia> A{Quantity{Float64}}(x, y, z) |> string
> "A{Quantity{Float64}}(123.0, 1.0 m, 2.0 kg)"
> ```

It doesn't seem to work well with custom types (it's `1.0 m` and no parsable).
I was wondering if this is a bug.

As it turns out, it is not a bug.
The `string` method for general `structs` is called `Base.print_to_string`, which uses the `print` method internally. This package is out of scope because I want to promise not to change the behavior of `Unitful`.

**Comment by michikawa07** [comment]
I agree with closing this issue as I am sure the bugs related to `NoUnits` have been fixed.
Sorry for all the trouble.

**Comment by singularitti** [comment]
No problem, I'm glad it is fixed. Thank you again!
